# HTML content handler sources

S_HTML := box_construct.c	\
	box_inspect.c		\
	box_manipulate.c	\
	box_normalise.c		\
	box_special.c		\
	box_textarea.c		\
	canvas.c		\
	css.c			\
	css_fetcher.c		\
	dom_event.c		\
	font.c			\
	form.c			\
	forms.c			\
	html.c			\
	imagemap.c		\
	inline_svg.c		\
	interaction.c		\
	layout.c		\
	layout_flex.c		\
	layout_grid.c		\
	media.c			\
	rebuild.c		\
	object.c		\
	redraw.c		\
	redraw_border.c		\
	script.c		\
	shadow.c		\
	table.c			\
	textselection.c		\
	webfont.c
