# -*- mode: makefile-gmake -*-
##
## tool setup for the framebuffer target
##

ifeq ($(origin GCCSDK_INSTALL_ENV),undefined)
  PKG_CONFIG := pkg-config
else
  PKG_CONFIG := PKG_CONFIG_LIBDIR="$(GCCSDK_INSTALL_ENV)/lib/pkgconfig" pkg-config                
endif

ifneq ($(origin GCCSDK_INSTALL_CROSSBIN),undefined)
  CC := $(wildcard $(GCCSDK_INSTALL_CROSSBIN)/*gcc)
  CXX := $(wildcard $(GCCSDK_INSTALL_CROSSBIN)/*g++)
endif

# Nintendo Switch (devkitA64/libnx) cross build
ifeq ($(HOST),aarch64-none-elf)
  CC := aarch64-none-elf-gcc
  CXX := aarch64-none-elf-g++
endif
