/* ANSI-C code produced by gperf version 3.3 */
/* Command-line: gperf --output-file=src/autogenerated_colors.c.tmp src/colors.gperf  */
/* Computed positions: -k'1,3,6-8,12-13' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 16 "src/colors.gperf"

#include <string.h>
#include "svgtiny.h"
#include "svgtiny_internal.h"

#line 23 "src/colors.gperf"
struct svgtiny_named_color;

#define TOTAL_KEYWORDS 147
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 20
#define MIN_HASH_VALUE 4
#define MAX_HASH_VALUE 565
/* maximum key range = 562, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
svgtiny_color_hash (register const char *str, register size_t len)
{
  static const unsigned short asso_values[] =
    {
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566,   5,  55,   0,
       35,   0,  75,  10,   5,   0, 566, 250,  10,  40,
       85,  60,  70, 144,   0,  20,  45,  10,  30, 185,
       95, 195, 566,   0, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566, 566, 566,
      566, 566, 566, 566, 566, 566, 566, 566
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[12]];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 12:
        hval += asso_values[(unsigned char)str[11]];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 11:
      case 10:
      case 9:
      case 8:
        hval += asso_values[(unsigned char)str[7]];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 5:
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]+2];
#if (defined __cplusplus && (__cplusplus >= 201703L || (__cplusplus >= 201103L && defined __clang__ && __clang_major__ + (__clang_minor__ >= 9) > 3))) || (defined __STDC_VERSION__ && __STDC_VERSION__ >= 202000L && ((defined __GNUC__ && __GNUC__ >= 10) || (defined __clang__ && __clang_major__ >= 9)))
      [[fallthrough]];
#elif (defined __GNUC__ && __GNUC__ >= 7) || (defined __clang__ && __clang_major__ >= 10)
      __attribute__ ((__fallthrough__));
#endif
      /*FALLTHROUGH*/
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static const struct svgtiny_named_color *
svgtiny_color_lookup (register const char *str, register size_t len)
{
#if (defined __GNUC__ && __GNUC__ + (__GNUC_MINOR__ >= 6) > 4) || (defined __clang__ && __clang_major__ >= 3)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif
  static const struct svgtiny_named_color wordlist[] =
    {
#line 45 "src/colors.gperf"
      {"cyan",		svgtiny_RGB(  0, 255, 255)},
#line 78 "src/colors.gperf"
      {"gray",		svgtiny_RGB(128, 128, 128)},
#line 39 "src/colors.gperf"
      {"chartreuse",	svgtiny_RGB(127, 255,   0)},
#line 79 "src/colors.gperf"
      {"grey",		svgtiny_RGB(128, 128, 128)},
#line 80 "src/colors.gperf"
      {"green",		svgtiny_RGB(  0, 128,   0)},
#line 98 "src/colors.gperf"
      {"lightgrey",	svgtiny_RGB(211, 211, 211)},
#line 97 "src/colors.gperf"
      {"lightgreen",	svgtiny_RGB(144, 238, 144)},
#line 96 "src/colors.gperf"
      {"lightgray",	svgtiny_RGB(211, 211, 211)},
#line 154 "src/colors.gperf"
      {"skyblue",	svgtiny_RGB(135, 206, 235)},
#line 157 "src/colors.gperf"
      {"slategrey",	svgtiny_RGB(112, 128, 144)},
#line 152 "src/colors.gperf"
      {"sienna",		svgtiny_RGB(160,  82,  45)},
#line 156 "src/colors.gperf"
      {"slategray",	svgtiny_RGB(112, 128, 144)},
#line 151 "src/colors.gperf"
      {"seashell",	svgtiny_RGB(255, 245, 238)},
#line 162 "src/colors.gperf"
      {"teal",		svgtiny_RGB(  0, 128, 128)},
#line 41 "src/colors.gperf"
      {"coral",		svgtiny_RGB(255, 127,  80)},
#line 100 "src/colors.gperf"
      {"lightsalmon",	svgtiny_RGB(255, 160, 122)},
#line 104 "src/colors.gperf"
      {"lightslategrey",	svgtiny_RGB(119, 136, 153)},
#line 32 "src/colors.gperf"
      {"black",		svgtiny_RGB(  0,   0,   0)},
#line 103 "src/colors.gperf"
      {"lightslategray",	svgtiny_RGB(119, 136, 153)},
#line 130 "src/colors.gperf"
      {"orange",		svgtiny_RGB(255, 165,   0)},
#line 131 "src/colors.gperf"
      {"orangered",	svgtiny_RGB(255,  69,   0)},
#line 31 "src/colors.gperf"
      {"bisque",		svgtiny_RGB(255, 228, 196)},
#line 107 "src/colors.gperf"
      {"lime",		svgtiny_RGB(  0, 255,   0)},
#line 144 "src/colors.gperf"
      {"red",		svgtiny_RGB(255,   0,   0)},
#line 108 "src/colors.gperf"
      {"limegreen",	svgtiny_RGB( 50, 205,  50)},
#line 93 "src/colors.gperf"
      {"lightcoral",	svgtiny_RGB(240, 128, 128)},
#line 146 "src/colors.gperf"
      {"royalblue",	svgtiny_RGB( 65, 105, 225)},
#line 109 "src/colors.gperf"
      {"linen",		svgtiny_RGB(250, 240, 230)},
#line 73 "src/colors.gperf"
      {"fuchsia",	svgtiny_RGB(255,   0, 255)},
#line 50 "src/colors.gperf"
      {"darkgreen",	svgtiny_RGB(  0, 100,   0)},
#line 92 "src/colors.gperf"
      {"lightblue",	svgtiny_RGB(173, 216, 230)},
#line 56 "src/colors.gperf"
      {"darkorchid",	svgtiny_RGB(153,  50, 204)},
#line 159 "src/colors.gperf"
      {"springgreen",	svgtiny_RGB(  0, 255, 127)},
#line 110 "src/colors.gperf"
      {"magenta",	svgtiny_RGB(255,   0, 255)},
#line 76 "src/colors.gperf"
      {"gold",		svgtiny_RGB(255, 215,   0)},
#line 132 "src/colors.gperf"
      {"orchid",		svgtiny_RGB(218, 112, 214)},
#line 155 "src/colors.gperf"
      {"slateblue",	svgtiny_RGB(106,  90, 205)},
#line 53 "src/colors.gperf"
      {"darkmagenta",	svgtiny_RGB(139, 0,   139)},
#line 46 "src/colors.gperf"
      {"darkblue",	svgtiny_RGB(  0,   0, 139)},
#line 105 "src/colors.gperf"
      {"lightsteelblue",	svgtiny_RGB(176, 196, 222)},
#line 153 "src/colors.gperf"
      {"silver",		svgtiny_RGB(192, 192, 192)},
#line 150 "src/colors.gperf"
      {"seagreen",	svgtiny_RGB( 46, 139,  87)},
#line 160 "src/colors.gperf"
      {"steelblue",	svgtiny_RGB( 70, 130, 180)},
#line 161 "src/colors.gperf"
      {"tan",		svgtiny_RGB(210, 180, 140)},
#line 139 "src/colors.gperf"
      {"peru",		svgtiny_RGB(205, 133,  63)},
#line 143 "src/colors.gperf"
      {"purple",		svgtiny_RGB(128,   0, 128)},
#line 57 "src/colors.gperf"
      {"darkred",	svgtiny_RGB(139,   0,   0)},
#line 122 "src/colors.gperf"
      {"mintcream",	svgtiny_RGB(245, 255, 250)},
#line 70 "src/colors.gperf"
      {"firebrick",	svgtiny_RGB(178,  34,  34)},
#line 101 "src/colors.gperf"
      {"lightseagreen",	svgtiny_RGB( 32, 178, 170)},
#line 54 "src/colors.gperf"
      {"darkolivegreen",	svgtiny_RGB( 85, 107,  47)},
#line 123 "src/colors.gperf"
      {"mistyrose",	svgtiny_RGB(255, 228, 225)},
#line 85 "src/colors.gperf"
      {"indigo",		svgtiny_RGB( 75,   0, 130)},
#line 127 "src/colors.gperf"
      {"oldlace",	svgtiny_RGB(253, 245, 230)},
#line 140 "src/colors.gperf"
      {"pink",		svgtiny_RGB(255, 192, 203)},
#line 58 "src/colors.gperf"
      {"darksalmon",	svgtiny_RGB(233, 150, 122)},
#line 88 "src/colors.gperf"
      {"lavender",	svgtiny_RGB(230, 230, 250)},
#line 86 "src/colors.gperf"
      {"ivory",		svgtiny_RGB(255, 255, 240)},
#line 124 "src/colors.gperf"
      {"moccasin",	svgtiny_RGB(255, 228, 181)},
#line 38 "src/colors.gperf"
      {"cadetblue",	svgtiny_RGB( 95, 158, 160)},
#line 64 "src/colors.gperf"
      {"darkviolet",	svgtiny_RGB(148,   0, 211)},
#line 147 "src/colors.gperf"
      {"saddlebrown",	svgtiny_RGB(139,  69,  19)},
#line 60 "src/colors.gperf"
      {"darkslateblue",	svgtiny_RGB( 72,  61, 139)},
#line 134 "src/colors.gperf"
      {"palegreen",	svgtiny_RGB(152, 251, 152)},
#line 158 "src/colors.gperf"
      {"snow",		svgtiny_RGB(255, 250, 250)},
#line 84 "src/colors.gperf"
      {"indianred",	svgtiny_RGB(205,  92,  92)},
#line 95 "src/colors.gperf"
      {"lightgoldenrodyellow",	svgtiny_RGB(250, 250, 210)},
#line 164 "src/colors.gperf"
      {"tomato",		svgtiny_RGB(255,  99,  71)},
#line 91 "src/colors.gperf"
      {"lemonchiffon",	svgtiny_RGB(255, 250, 205)},
#line 99 "src/colors.gperf"
      {"lightpink",	svgtiny_RGB(255, 182, 193)},
#line 111 "src/colors.gperf"
      {"maroon",		svgtiny_RGB(128,   0,   0)},
#line 89 "src/colors.gperf"
      {"lavenderblush",	svgtiny_RGB(255, 240, 245)},
#line 165 "src/colors.gperf"
      {"turquoise",	svgtiny_RGB( 64, 224, 208)},
#line 55 "src/colors.gperf"
      {"darkorange",	svgtiny_RGB(255, 140,   0)},
#line 126 "src/colors.gperf"
      {"navy",		svgtiny_RGB(  0,   0, 128)},
#line 69 "src/colors.gperf"
      {"dodgerblue",	svgtiny_RGB( 30, 144, 255)},
#line 72 "src/colors.gperf"
      {"forestgreen",	svgtiny_RGB( 34, 139,  34)},
#line 121 "src/colors.gperf"
      {"midnightblue",	svgtiny_RGB( 25,  25, 112)},
#line 116 "src/colors.gperf"
      {"mediumseagreen",	svgtiny_RGB( 60, 179, 113)},
#line 59 "src/colors.gperf"
      {"darkseagreen",	svgtiny_RGB(143, 188, 143)},
#line 27 "src/colors.gperf"
      {"aqua",		svgtiny_RGB(  0, 255, 255)},
#line 29 "src/colors.gperf"
      {"azure",		svgtiny_RGB(240, 255, 255)},
#line 148 "src/colors.gperf"
      {"salmon",		svgtiny_RGB(250, 128, 114)},
#line 167 "src/colors.gperf"
      {"wheat",		svgtiny_RGB(245, 222, 179)},
#line 36 "src/colors.gperf"
      {"brown",		svgtiny_RGB(165,  42,  42)},
#line 28 "src/colors.gperf"
      {"aquamarine",	svgtiny_RGB(127, 255, 212)},
#line 40 "src/colors.gperf"
      {"chocolate",	svgtiny_RGB(210, 105,  30)},
#line 90 "src/colors.gperf"
      {"lawngreen",	svgtiny_RGB(124, 252,   0)},
#line 149 "src/colors.gperf"
      {"sandybrown",	svgtiny_RGB(244, 164,  96)},
#line 94 "src/colors.gperf"
      {"lightcyan",	svgtiny_RGB(224, 255, 255)},
#line 166 "src/colors.gperf"
      {"violet",		svgtiny_RGB(238, 130, 238)},
#line 106 "src/colors.gperf"
      {"lightyellow",	svgtiny_RGB(255, 255, 224)},
#line 113 "src/colors.gperf"
      {"mediumblue",	svgtiny_RGB(  0,   0, 205)},
#line 138 "src/colors.gperf"
      {"peachpuff",	svgtiny_RGB(255, 218, 185)},
#line 81 "src/colors.gperf"
      {"greenyellow",	svgtiny_RGB(173, 255,  47)},
#line 26 "src/colors.gperf"
      {"antiquewhite",	svgtiny_RGB(250, 235, 215)},
#line 34 "src/colors.gperf"
      {"blue",		svgtiny_RGB(  0,   0, 255)},
#line 120 "src/colors.gperf"
      {"mediumvioletred",	svgtiny_RGB(199,  21, 133)},
#line 115 "src/colors.gperf"
      {"mediumpurple",	svgtiny_RGB(147, 112, 219)},
#line 77 "src/colors.gperf"
      {"goldenrod",	svgtiny_RGB(218, 165,  32)},
#line 33 "src/colors.gperf"
      {"blanchedalmond",	svgtiny_RGB(255, 235, 205)},
#line 87 "src/colors.gperf"
      {"khaki",		svgtiny_RGB(240, 230, 140)},
#line 141 "src/colors.gperf"
      {"plum",		svgtiny_RGB(221, 160, 221)},
#line 114 "src/colors.gperf"
      {"mediumorchid",	svgtiny_RGB(186,  85, 211)},
#line 145 "src/colors.gperf"
      {"rosybrown",	svgtiny_RGB(188, 143, 143)},
#line 117 "src/colors.gperf"
      {"mediumslateblue",	svgtiny_RGB(123, 104, 238)},
#line 63 "src/colors.gperf"
      {"darkturquoise",	svgtiny_RGB(  0, 206, 209)},
#line 136 "src/colors.gperf"
      {"palevioletred",	svgtiny_RGB(219, 112, 147)},
#line 137 "src/colors.gperf"
      {"papayawhip",	svgtiny_RGB(255, 239, 213)},
#line 118 "src/colors.gperf"
      {"mediumspringgreen",	svgtiny_RGB(  0, 250, 154)},
#line 51 "src/colors.gperf"
      {"darkgrey",	svgtiny_RGB(169, 169, 169)},
#line 119 "src/colors.gperf"
      {"mediumturquoise",	svgtiny_RGB( 72, 209, 204)},
#line 49 "src/colors.gperf"
      {"darkgray",	svgtiny_RGB(169, 169, 169)},
#line 48 "src/colors.gperf"
      {"darkgoldenrod",	svgtiny_RGB(184, 134,  11)},
#line 68 "src/colors.gperf"
      {"dimgrey",	svgtiny_RGB(105, 105, 105)},
#line 67 "src/colors.gperf"
      {"dimgray",	svgtiny_RGB(105, 105, 105)},
#line 82 "src/colors.gperf"
      {"honeydew",	svgtiny_RGB(240, 255, 240)},
#line 30 "src/colors.gperf"
      {"beige",		svgtiny_RGB(245, 245, 220)},
#line 163 "src/colors.gperf"
      {"thistle",	svgtiny_RGB(216, 191, 216)},
#line 43 "src/colors.gperf"
      {"cornsilk",	svgtiny_RGB(255, 248, 220)},
#line 128 "src/colors.gperf"
      {"olive",		svgtiny_RGB(128, 128,   0)},
#line 35 "src/colors.gperf"
      {"blueviolet",	svgtiny_RGB(138,  43, 226)},
#line 112 "src/colors.gperf"
      {"mediumaquamarine",	svgtiny_RGB(102, 205, 170)},
#line 42 "src/colors.gperf"
      {"cornflowerblue",	svgtiny_RGB(100, 149, 237)},
#line 25 "src/colors.gperf"
      {"aliceblue",	svgtiny_RGB(240, 248, 255)},
#line 142 "src/colors.gperf"
      {"powderblue",	svgtiny_RGB(176, 224, 230)},
#line 135 "src/colors.gperf"
      {"paleturquoise",	svgtiny_RGB(175, 238, 238)},
#line 62 "src/colors.gperf"
      {"darkslategrey",	svgtiny_RGB( 47,  79,  79)},
#line 52 "src/colors.gperf"
      {"darkkhaki",	svgtiny_RGB(189, 183, 107)},
#line 61 "src/colors.gperf"
      {"darkslategray",	svgtiny_RGB( 47,  79,  79)},
#line 75 "src/colors.gperf"
      {"ghostwhite",	svgtiny_RGB(248, 248, 255)},
#line 129 "src/colors.gperf"
      {"olivedrab",	svgtiny_RGB(107, 142,  35)},
#line 133 "src/colors.gperf"
      {"palegoldenrod",	svgtiny_RGB(238, 232, 170)},
#line 47 "src/colors.gperf"
      {"darkcyan",	svgtiny_RGB(  0, 139, 139)},
#line 83 "src/colors.gperf"
      {"hotpink",	svgtiny_RGB(255, 105, 180)},
#line 74 "src/colors.gperf"
      {"gainsboro",	svgtiny_RGB(220, 220, 220)},
#line 65 "src/colors.gperf"
      {"deeppink",	svgtiny_RGB(255,  20, 147)},
#line 44 "src/colors.gperf"
      {"crimson",	svgtiny_RGB(220,  20,  60)},
#line 37 "src/colors.gperf"
      {"burlywood",	svgtiny_RGB(222, 184, 135)},
#line 71 "src/colors.gperf"
      {"floralwhite",	svgtiny_RGB(255, 250, 240)},
#line 168 "src/colors.gperf"
      {"white",		svgtiny_RGB(255, 255, 255)},
#line 125 "src/colors.gperf"
      {"navajowhite",	svgtiny_RGB(255, 222, 173)},
#line 170 "src/colors.gperf"
      {"yellow",		svgtiny_RGB(255, 255,   0)},
#line 171 "src/colors.gperf"
      {"yellowgreen",	svgtiny_RGB(154, 205,  50)},
#line 102 "src/colors.gperf"
      {"lightskyblue",	svgtiny_RGB(135, 206, 250)},
#line 66 "src/colors.gperf"
      {"deepskyblue",	svgtiny_RGB(  0, 191, 255)},
#line 169 "src/colors.gperf"
      {"whitesmoke",	svgtiny_RGB(245, 245, 245)}
    };
#if (defined __GNUC__ && __GNUC__ + (__GNUC_MINOR__ >= 6) > 4) || (defined __clang__ && __clang_major__ >= 3)
#pragma GCC diagnostic pop
#endif

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = svgtiny_color_hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          register const struct svgtiny_named_color *resword;

          switch (key - 4)
            {
              case 0:
                if (len == 4)
                  {
                    resword = &wordlist[0];
                    goto compare;
                  }
                break;
              case 10:
                if (len == 4)
                  {
                    resword = &wordlist[1];
                    goto compare;
                  }
                break;
              case 16:
                if (len == 10)
                  {
                    resword = &wordlist[2];
                    goto compare;
                  }
                break;
              case 20:
                if (len == 4)
                  {
                    resword = &wordlist[3];
                    goto compare;
                  }
                break;
              case 21:
                if (len == 5)
                  {
                    resword = &wordlist[4];
                    goto compare;
                  }
                break;
              case 25:
                if (len == 9)
                  {
                    resword = &wordlist[5];
                    goto compare;
                  }
                break;
              case 26:
                if (len == 10)
                  {
                    resword = &wordlist[6];
                    goto compare;
                  }
                break;
              case 30:
                if (len == 9)
                  {
                    resword = &wordlist[7];
                    goto compare;
                  }
                break;
              case 33:
                if (len == 7)
                  {
                    resword = &wordlist[8];
                    goto compare;
                  }
                break;
              case 35:
                if (len == 9)
                  {
                    resword = &wordlist[9];
                    goto compare;
                  }
                break;
              case 37:
                if (len == 6)
                  {
                    resword = &wordlist[10];
                    goto compare;
                  }
                break;
              case 40:
                if (len == 9)
                  {
                    resword = &wordlist[11];
                    goto compare;
                  }
                break;
              case 44:
                if (len == 8)
                  {
                    resword = &wordlist[12];
                    goto compare;
                  }
                break;
              case 45:
                if (len == 4)
                  {
                    resword = &wordlist[13];
                    goto compare;
                  }
                break;
              case 46:
                if (len == 5)
                  {
                    resword = &wordlist[14];
                    goto compare;
                  }
                break;
              case 52:
                if (len == 11)
                  {
                    resword = &wordlist[15];
                    goto compare;
                  }
                break;
              case 55:
                if (len == 14)
                  {
                    resword = &wordlist[16];
                    goto compare;
                  }
                break;
              case 56:
                if (len == 5)
                  {
                    resword = &wordlist[17];
                    goto compare;
                  }
                break;
              case 60:
                if (len == 14)
                  {
                    resword = &wordlist[18];
                    goto compare;
                  }
                break;
              case 62:
                if (len == 6)
                  {
                    resword = &wordlist[19];
                    goto compare;
                  }
                break;
              case 65:
                if (len == 9)
                  {
                    resword = &wordlist[20];
                    goto compare;
                  }
                break;
              case 67:
                if (len == 6)
                  {
                    resword = &wordlist[21];
                    goto compare;
                  }
                break;
              case 70:
                if (len == 4)
                  {
                    resword = &wordlist[22];
                    goto compare;
                  }
                break;
              case 74:
                if (len == 3)
                  {
                    resword = &wordlist[23];
                    goto compare;
                  }
                break;
              case 75:
                if (len == 9)
                  {
                    resword = &wordlist[24];
                    goto compare;
                  }
                break;
              case 76:
                if (len == 10)
                  {
                    resword = &wordlist[25];
                    goto compare;
                  }
                break;
              case 80:
                if (len == 9)
                  {
                    resword = &wordlist[26];
                    goto compare;
                  }
                break;
              case 81:
                if (len == 5)
                  {
                    resword = &wordlist[27];
                    goto compare;
                  }
                break;
              case 83:
                if (len == 7)
                  {
                    resword = &wordlist[28];
                    goto compare;
                  }
                break;
              case 85:
                if (len == 9)
                  {
                    resword = &wordlist[29];
                    goto compare;
                  }
                break;
              case 90:
                if (len == 9)
                  {
                    resword = &wordlist[30];
                    goto compare;
                  }
                break;
              case 91:
                if (len == 10)
                  {
                    resword = &wordlist[31];
                    goto compare;
                  }
                break;
              case 92:
                if (len == 11)
                  {
                    resword = &wordlist[32];
                    goto compare;
                  }
                break;
              case 93:
                if (len == 7)
                  {
                    resword = &wordlist[33];
                    goto compare;
                  }
                break;
              case 95:
                if (len == 4)
                  {
                    resword = &wordlist[34];
                    goto compare;
                  }
                break;
              case 97:
                if (len == 6)
                  {
                    resword = &wordlist[35];
                    goto compare;
                  }
                break;
              case 100:
                if (len == 9)
                  {
                    resword = &wordlist[36];
                    goto compare;
                  }
                break;
              case 102:
                if (len == 11)
                  {
                    resword = &wordlist[37];
                    goto compare;
                  }
                break;
              case 104:
                if (len == 8)
                  {
                    resword = &wordlist[38];
                    goto compare;
                  }
                break;
              case 105:
                if (len == 14)
                  {
                    resword = &wordlist[39];
                    goto compare;
                  }
                break;
              case 107:
                if (len == 6)
                  {
                    resword = &wordlist[40];
                    goto compare;
                  }
                break;
              case 109:
                if (len == 8)
                  {
                    resword = &wordlist[41];
                    goto compare;
                  }
                break;
              case 110:
                if (len == 9)
                  {
                    resword = &wordlist[42];
                    goto compare;
                  }
                break;
              case 114:
                if (len == 3)
                  {
                    resword = &wordlist[43];
                    goto compare;
                  }
                break;
              case 115:
                if (len == 4)
                  {
                    resword = &wordlist[44];
                    goto compare;
                  }
                break;
              case 117:
                if (len == 6)
                  {
                    resword = &wordlist[45];
                    goto compare;
                  }
                break;
              case 118:
                if (len == 7)
                  {
                    resword = &wordlist[46];
                    goto compare;
                  }
                break;
              case 120:
                if (len == 9)
                  {
                    resword = &wordlist[47];
                    goto compare;
                  }
                break;
              case 125:
                if (len == 9)
                  {
                    resword = &wordlist[48];
                    goto compare;
                  }
                break;
              case 129:
                if (len == 13)
                  {
                    resword = &wordlist[49];
                    goto compare;
                  }
                break;
              case 130:
                if (len == 14)
                  {
                    resword = &wordlist[50];
                    goto compare;
                  }
                break;
              case 135:
                if (len == 9)
                  {
                    resword = &wordlist[51];
                    goto compare;
                  }
                break;
              case 137:
                if (len == 6)
                  {
                    resword = &wordlist[52];
                    goto compare;
                  }
                break;
              case 138:
                if (len == 7)
                  {
                    resword = &wordlist[53];
                    goto compare;
                  }
                break;
              case 140:
                if (len == 4)
                  {
                    resword = &wordlist[54];
                    goto compare;
                  }
                break;
              case 141:
                if (len == 10)
                  {
                    resword = &wordlist[55];
                    goto compare;
                  }
                break;
              case 144:
                if (len == 8)
                  {
                    resword = &wordlist[56];
                    goto compare;
                  }
                break;
              case 145:
                if (len == 5)
                  {
                    resword = &wordlist[57];
                    goto compare;
                  }
                break;
              case 149:
                if (len == 8)
                  {
                    resword = &wordlist[58];
                    goto compare;
                  }
                break;
              case 155:
                if (len == 9)
                  {
                    resword = &wordlist[59];
                    goto compare;
                  }
                break;
              case 156:
                if (len == 10)
                  {
                    resword = &wordlist[60];
                    goto compare;
                  }
                break;
              case 157:
                if (len == 11)
                  {
                    resword = &wordlist[61];
                    goto compare;
                  }
                break;
              case 159:
                if (len == 13)
                  {
                    resword = &wordlist[62];
                    goto compare;
                  }
                break;
              case 160:
                if (len == 9)
                  {
                    resword = &wordlist[63];
                    goto compare;
                  }
                break;
              case 164:
                if (len == 4)
                  {
                    resword = &wordlist[64];
                    goto compare;
                  }
                break;
              case 165:
                if (len == 9)
                  {
                    resword = &wordlist[65];
                    goto compare;
                  }
                break;
              case 166:
                if (len == 20)
                  {
                    resword = &wordlist[66];
                    goto compare;
                  }
                break;
              case 167:
                if (len == 6)
                  {
                    resword = &wordlist[67];
                    goto compare;
                  }
                break;
              case 168:
                if (len == 12)
                  {
                    resword = &wordlist[68];
                    goto compare;
                  }
                break;
              case 170:
                if (len == 9)
                  {
                    resword = &wordlist[69];
                    goto compare;
                  }
                break;
              case 172:
                if (len == 6)
                  {
                    resword = &wordlist[70];
                    goto compare;
                  }
                break;
              case 174:
                if (len == 13)
                  {
                    resword = &wordlist[71];
                    goto compare;
                  }
                break;
              case 175:
                if (len == 9)
                  {
                    resword = &wordlist[72];
                    goto compare;
                  }
                break;
              case 176:
                if (len == 10)
                  {
                    resword = &wordlist[73];
                    goto compare;
                  }
                break;
              case 180:
                if (len == 4)
                  {
                    resword = &wordlist[74];
                    goto compare;
                  }
                break;
              case 181:
                if (len == 10)
                  {
                    resword = &wordlist[75];
                    goto compare;
                  }
                break;
              case 182:
                if (len == 11)
                  {
                    resword = &wordlist[76];
                    goto compare;
                  }
                break;
              case 183:
                if (len == 12)
                  {
                    resword = &wordlist[77];
                    goto compare;
                  }
                break;
              case 185:
                if (len == 14)
                  {
                    resword = &wordlist[78];
                    goto compare;
                  }
                break;
              case 188:
                if (len == 12)
                  {
                    resword = &wordlist[79];
                    goto compare;
                  }
                break;
              case 190:
                if (len == 4)
                  {
                    resword = &wordlist[80];
                    goto compare;
                  }
                break;
              case 191:
                if (len == 5)
                  {
                    resword = &wordlist[81];
                    goto compare;
                  }
                break;
              case 192:
                if (len == 6)
                  {
                    resword = &wordlist[82];
                    goto compare;
                  }
                break;
              case 196:
                if (len == 5)
                  {
                    resword = &wordlist[83];
                    goto compare;
                  }
                break;
              case 200:
                if (len == 5)
                  {
                    resword = &wordlist[84];
                    goto compare;
                  }
                break;
              case 201:
                if (len == 10)
                  {
                    resword = &wordlist[85];
                    goto compare;
                  }
                break;
              case 209:
                if (len == 9)
                  {
                    resword = &wordlist[86];
                    goto compare;
                  }
                break;
              case 210:
                if (len == 9)
                  {
                    resword = &wordlist[87];
                    goto compare;
                  }
                break;
              case 211:
                if (len == 10)
                  {
                    resword = &wordlist[88];
                    goto compare;
                  }
                break;
              case 215:
                if (len == 9)
                  {
                    resword = &wordlist[89];
                    goto compare;
                  }
                break;
              case 221:
                if (len == 6)
                  {
                    resword = &wordlist[90];
                    goto compare;
                  }
                break;
              case 222:
                if (len == 11)
                  {
                    resword = &wordlist[91];
                    goto compare;
                  }
                break;
              case 226:
                if (len == 10)
                  {
                    resword = &wordlist[92];
                    goto compare;
                  }
                break;
              case 230:
                if (len == 9)
                  {
                    resword = &wordlist[93];
                    goto compare;
                  }
                break;
              case 232:
                if (len == 11)
                  {
                    resword = &wordlist[94];
                    goto compare;
                  }
                break;
              case 238:
                if (len == 12)
                  {
                    resword = &wordlist[95];
                    goto compare;
                  }
                break;
              case 240:
                if (len == 4)
                  {
                    resword = &wordlist[96];
                    goto compare;
                  }
                break;
              case 241:
                if (len == 15)
                  {
                    resword = &wordlist[97];
                    goto compare;
                  }
                break;
              case 243:
                if (len == 12)
                  {
                    resword = &wordlist[98];
                    goto compare;
                  }
                break;
              case 245:
                if (len == 9)
                  {
                    resword = &wordlist[99];
                    goto compare;
                  }
                break;
              case 250:
                if (len == 14)
                  {
                    resword = &wordlist[100];
                    goto compare;
                  }
                break;
              case 251:
                if (len == 5)
                  {
                    resword = &wordlist[101];
                    goto compare;
                  }
                break;
              case 255:
                if (len == 4)
                  {
                    resword = &wordlist[102];
                    goto compare;
                  }
                break;
              case 258:
                if (len == 12)
                  {
                    resword = &wordlist[103];
                    goto compare;
                  }
                break;
              case 260:
                if (len == 9)
                  {
                    resword = &wordlist[104];
                    goto compare;
                  }
                break;
              case 261:
                if (len == 15)
                  {
                    resword = &wordlist[105];
                    goto compare;
                  }
                break;
              case 263:
                if (len == 13)
                  {
                    resword = &wordlist[106];
                    goto compare;
                  }
                break;
              case 269:
                if (len == 13)
                  {
                    resword = &wordlist[107];
                    goto compare;
                  }
                break;
              case 271:
                if (len == 10)
                  {
                    resword = &wordlist[108];
                    goto compare;
                  }
                break;
              case 278:
                if (len == 17)
                  {
                    resword = &wordlist[109];
                    goto compare;
                  }
                break;
              case 279:
                if (len == 8)
                  {
                    resword = &wordlist[110];
                    goto compare;
                  }
                break;
              case 281:
                if (len == 15)
                  {
                    resword = &wordlist[111];
                    goto compare;
                  }
                break;
              case 284:
                if (len == 8)
                  {
                    resword = &wordlist[112];
                    goto compare;
                  }
                break;
              case 289:
                if (len == 13)
                  {
                    resword = &wordlist[113];
                    goto compare;
                  }
                break;
              case 293:
                if (len == 7)
                  {
                    resword = &wordlist[114];
                    goto compare;
                  }
                break;
              case 298:
                if (len == 7)
                  {
                    resword = &wordlist[115];
                    goto compare;
                  }
                break;
              case 299:
                if (len == 8)
                  {
                    resword = &wordlist[116];
                    goto compare;
                  }
                break;
              case 306:
                if (len == 5)
                  {
                    resword = &wordlist[117];
                    goto compare;
                  }
                break;
              case 308:
                if (len == 7)
                  {
                    resword = &wordlist[118];
                    goto compare;
                  }
                break;
              case 309:
                if (len == 8)
                  {
                    resword = &wordlist[119];
                    goto compare;
                  }
                break;
              case 311:
                if (len == 5)
                  {
                    resword = &wordlist[120];
                    goto compare;
                  }
                break;
              case 316:
                if (len == 10)
                  {
                    resword = &wordlist[121];
                    goto compare;
                  }
                break;
              case 321:
                if (len == 16)
                  {
                    resword = &wordlist[122];
                    goto compare;
                  }
                break;
              case 330:
                if (len == 14)
                  {
                    resword = &wordlist[123];
                    goto compare;
                  }
                break;
              case 335:
                if (len == 9)
                  {
                    resword = &wordlist[124];
                    goto compare;
                  }
                break;
              case 336:
                if (len == 10)
                  {
                    resword = &wordlist[125];
                    goto compare;
                  }
                break;
              case 338:
                if (len == 13)
                  {
                    resword = &wordlist[126];
                    goto compare;
                  }
                break;
              case 344:
                if (len == 13)
                  {
                    resword = &wordlist[127];
                    goto compare;
                  }
                break;
              case 345:
                if (len == 9)
                  {
                    resword = &wordlist[128];
                    goto compare;
                  }
                break;
              case 349:
                if (len == 13)
                  {
                    resword = &wordlist[129];
                    goto compare;
                  }
                break;
              case 350:
                if (len == 10)
                  {
                    resword = &wordlist[130];
                    goto compare;
                  }
                break;
              case 355:
                if (len == 9)
                  {
                    resword = &wordlist[131];
                    goto compare;
                  }
                break;
              case 364:
                if (len == 13)
                  {
                    resword = &wordlist[132];
                    goto compare;
                  }
                break;
              case 369:
                if (len == 8)
                  {
                    resword = &wordlist[133];
                    goto compare;
                  }
                break;
              case 373:
                if (len == 7)
                  {
                    resword = &wordlist[134];
                    goto compare;
                  }
                break;
              case 380:
                if (len == 9)
                  {
                    resword = &wordlist[135];
                    goto compare;
                  }
                break;
              case 384:
                if (len == 8)
                  {
                    resword = &wordlist[136];
                    goto compare;
                  }
                break;
              case 398:
                if (len == 7)
                  {
                    resword = &wordlist[137];
                    goto compare;
                  }
                break;
              case 410:
                if (len == 9)
                  {
                    resword = &wordlist[138];
                    goto compare;
                  }
                break;
              case 426:
                if (len == 11)
                  {
                    resword = &wordlist[139];
                    goto compare;
                  }
                break;
              case 436:
                if (len == 5)
                  {
                    resword = &wordlist[140];
                    goto compare;
                  }
                break;
              case 437:
                if (len == 11)
                  {
                    resword = &wordlist[141];
                    goto compare;
                  }
                break;
              case 467:
                if (len == 6)
                  {
                    resword = &wordlist[142];
                    goto compare;
                  }
                break;
              case 482:
                if (len == 11)
                  {
                    resword = &wordlist[143];
                    goto compare;
                  }
                break;
              case 483:
                if (len == 12)
                  {
                    resword = &wordlist[144];
                    goto compare;
                  }
                break;
              case 552:
                if (len == 11)
                  {
                    resword = &wordlist[145];
                    goto compare;
                  }
                break;
              case 561:
                if (len == 10)
                  {
                    resword = &wordlist[146];
                    goto compare;
                  }
                break;
            }
          return (struct svgtiny_named_color *) 0;
        compare:
          {
            register const char *s = resword->name;

            if (*str == *s && !memcmp (str + 1, s + 1, len - 1))
              return resword;
          }
        }
    }
  return (struct svgtiny_named_color *) 0;
}
