# Raw-string ("uninterpreted value") properties added for the Switch port.
# The value text is cascaded by LibCSS and interpreted by the client.
# (name, inherited)
RAW_PROPS = [
    ('border_top_left_radius', 0),
    ('border_top_right_radius', 0),
    ('border_bottom_right_radius', 0),
    ('border_bottom_left_radius', 0),
    ('box_shadow', 0),
    ('text_shadow', 1),
    ('transform', 0),
    ('grid_template_columns', 0),
    ('grid_template_rows', 0),
    ('grid_template_areas', 0),
    ('grid_column_start', 0),
    ('grid_column_end', 0),
    ('grid_row_start', 0),
    ('grid_row_end', 0),
    ('grid_auto_flow', 0),
    ('grid_auto_columns', 0),
    ('grid_auto_rows', 0),
    ('row_gap', 0),
    ('justify_items', 0),
    ('object_fit', 0),
    ('aspect_ratio', 0),
    ('text_overflow', 0),
    ('overflow_wrap', 1),
    ('word_break', 1),
    ('background_size', 0),
    ('filter', 0),
    ('transform_origin', 0),
    ('object_position', 0),
    ('justify_self', 0),
    ('pointer_events', 1),
    ('line_clamp', 0),
    ('mask_image', 0),
    ('mask_size', 0),
    ('mask_position', 0),
    ('mask_repeat', 0),
    ('mask', 0),
]
FIRST_ID = 0x07e
